### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by MenHimChan** [isl-org/lang-seg#48]
Traceback (most recent call last):
  File "/home/airs/Clip_Seg/lang-seg/prepare_ade20k.py", line 9, in <module>
    from encoding.utils import download, mkdir
  File "/home/airs/anaconda3/lib/python3.9/site-packages/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, parallel, utils, models, datasets, transforms
  File "/home/airs/anaconda3/lib/python3.9/site-packages/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/home/airs/anaconda3/lib/python3.9/site-packages/encoding/nn/encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "/home/airs/anaconda3/lib/python3.9/site-packages/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/home/airs/anaconda3/lib/python3.9/site-packages/encoding/functions/encoding.py", line 17, in <module>
    from encoding import gpu
ImportError: cannot import name 'gpu' from partially initialized module 'encoding' (most likely due to a circular import) (/home/airs/anaconda3/lib/python3.9/site-packages/encoding/__init__.py)

**Comment by enghish** [comment]
Same error with me

**Comment by lmc2000** [comment]
Failed to build installable wheels for some pyproject.toml based projects (torch-encoding)
